cvpaperchallenge/Ascender

LICENSE
ascender/.flake8
ascender/.gitignore
ascender/Makefile
ascender/poetry.lock
ascender/poetry.toml
ascender/pyproject.toml

- Add license file.
- Add setting file for poetry.
- Add setting file for flake8.
- Add ignore files.

Add setting files

---

ascender/environments/Dockerfile
ascender/environments/development_gpu/docker-compose.yaml

- Add docker files for development.

Add Dockerfile and compose file

---

.flake8
.github/workflows/lint-and-test.yaml
Makefile
poetry.lock
pyproject.toml

https://github.com/cvpaperchallenge/Ascender/issues/5
remove pysen and use bare formatters.
run following command.
```
% make format
% make lint
```
NA

remove pysen

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

https://github.com/cvpaperchallenge/Ascender/issues/9
add batch about license and CI
NA
NA

adding batch

---

poetry.lock
pyproject.toml

https://github.com/cvpaperchallenge/Ascender/issues/11
- Update some lib's version.
- Only `mypy` is minor version update else are patch version update. 
- Add some contents to `pyproject.toml`.  
`poetry run make test-all` successfully finishes same as before change.
NA

#11 chore: update pyproject.toml

---

environments/Dockerfile

https://github.com/cvpaperchallenge/Ascender/issues/15
Remove old keys and fetch new ones.
Following process successfully work both cpu and gpu env.
```
$ sudo docker-compose build --no-cache
$ sudo docker-compose up -d
$ sudo docker-compose exec core bash
% make test-all
```
I'll merge this without review because this change this exactly same as already reviewed PR in melon. https://github.com/cvpaperchallenge/melon/pull/45

#15 chore: reflect nvida gpg repo key update

---

.github/workflows/lint-and-test.yaml
README.md

#13 
- Add matrix to CI for supporting multiple Python version. For now only Python 3.9 is added.
Check CI result.
NA

#13 chore: add python3.9 to CI

---

README.md

#19 
- Add feature explanation of Ascender.
- Update docker, docker-compose installation command.
Please follow the installation step written in `README.md` (It worked at my local PC).
NA

#19 docs: update README.md

---

.editorconfig
src/sass/main.scss

None
It makes keeping same style every developer easy.
I believe this is needed even if we will introduce some lint tools.
Open same file with your favorite editor which supports editorconfig. 
Changing main.scss because it was not followed Sass official style.

Introduce .editorconfig

---

.gitignore
build/index.html
src/sass/main.scss

None
I put index.html in /build directory. I know this maybe bad idea. However we
have to put relative path between index.html and main.css is the same as when we
places them in the master branch. Otherwise our release script or our
development process get hard.
We don't have concrete agreement how many breakpoints we should have, how big,
blah blah blah. But I think this change is enough to demonstrate how we use it.
Build it and open in browser.
None

CSS Media Query by SCSS

---

build/index.html

https://github.com/cvpaperchallenge/Ascender/pull/27#pullrequestreview-1032513331
None
Otherwise when HTML and CSS file not at document root, you cannot load CSS
correctly.
None

Reference CSS file relatively

---

.editorconfig
.prettierrc
.stylelintrc.json
build/index.html
package-lock.json
package.json
src/sass/main.scss

None
Introduce linter; prettier is for HTML, stylelint is for SCSS
run `make shell` and  `npm run lint:fix`
None

Introduce linter; prettier is for HTML, stylelint is for SCSS

---

package.json

https://github.com/cvpaperchallenge/Ascender/pull/31#pullrequestreview-1033610695
None
Read package.json
None

Write author field of package.json

---

build/index.html
src/sass/main.scss

NA
- add title
- add author
- adjust spacing
Please build and check index.html from browser.
We need to implement centerize part of horizon.

feat: add author component.

---

.editorconfig
build/ascender.js
build/index.html
package.json
src/sass/main.scss

Implement Carousel Slider Component

---

build/index.html
src/sass/main.scss

NA
- add button feature
- add resources by using button feature
- build sass and check though browser.
NA

feat: add button feature

---

README.md
environments/Dockerfile
environments/cpu/docker-compose.yaml
environments/gpu/docker-compose.yaml

https://github.com/cvpaperchallenge/Ascender/issues/38
Add `UID` and `GID` to build argument of docker compose file. 
Please edit `UID` and `GID` values of `docker-compose.yaml`, and run following commands: 
```bash
$ sudo docker compose build --no-cache
$ sudo docker compose up -d
$ sudo docker compose exec core bash
$ poetry install
```
NA

fix: add UID and GID to build arg.

---

src/sass/main.scss

Set default text color

---

build/index.html
src/sass/main.scss

NA
Replace placeholder values by actual NeDDF paper's values.
Please build and check HTML file through browser.
NA

feat: replace placeholder by actual value

---

build/index.html
src/sass/main.scss

It makes all children of side-by-side element same width.

Implement even class as option of side-by-side class

---

build/ascender.js
build/index.html
src/sass/main.scss

NA
Add draft contents for project page.
Build and check through the browser.
NA

feat: add draft contents

---

build/index.html
build/manifest.json

Add meta tags for og and twitter card and favicon

---

build/index.html
src/sass/main.scss

Implement CSS class to align item top as option of side-by-side class.

---

build/index.html

NA
Add some info to meta
NA
NA

chore: add meta data

---

build/index.html
src/sass/main.scss

Show brand logo

---

build/index.html
src/sass/main.scss

Centerize paper title

---

build/ascender.js
build/index.html

Fix Carousel slider; show dots

---

README.md
environments/Dockerfile
poetry.toml

NA
Add followings to FAQ:
- Use Ascender without Docker
- Compatibility issue between PyTorch and Poetry
- Change the Python version to run CI jobs
Please read the updated README.md.
NA

docs: add questions to FAQ

---

README.md
environments/Dockerfile
environments/cpu/docker-compose.yaml
environments/gpu/docker-compose.yaml
poetry.toml

NA
- switch poetry version to 1.2 beta
- load UID and GIU from environmental variables
- add `poetry.toml` for the case which user want to use Ascender without Docker
- extend FAQ
All feature is already tested.
NA

feat: merge develop branch into master
